# Generated by Django 4.0.2 on 2022-02-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='time',
            field=models.TimeField(default=2),
            preserve_default=False,
        ),
    ]
